# Generated by Django 2.2.6 on 2019-11-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(choices=[('QU', "Queen's Univeristy"), ('UT', 'University of Toronto'), ('UW', 'University of Waterloo'), ('UWO', 'University of Western Ontario'), ('UG', 'Unviersity of Guelph')], max_length=4),
        ),
    ]
