# Generated by Django 2.2.6 on 2019-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTimeEdited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
