# Generated by Django 2.2.6 on 2019-11-21 01:19

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_course_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='posts',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Post'),
        ),
    ]
