# Generated by Django 2.2.6 on 2019-11-21 01:37

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191120_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='posts',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Post'),
        ),
    ]
