# Generated by Django 2.2.6 on 2019-12-21 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20191120_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dateTimePosted', models.DateTimeField(auto_now_add=True)),
                ('dateTimeEdited', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='fileContent',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='textContent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(choices=[('QU', "Queen's University"), ('UT', 'University of Toronto'), ('UW', 'University of Waterloo'), ('UWO', 'University of Western Ontario'), ('UG', 'University of Guelph')], max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Course'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dateTimePosted', models.DateTimeField(auto_now_add=True)),
                ('dateTimeEdited', models.DateTimeField(auto_now=True, null=True)),
                ('likesCount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to=settings.AUTH_USER_MODEL)),
                ('comments', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Comment')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.Content')),
                ('likes', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='replies',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Reply'),
        ),
    ]
