# Generated by Django 2.2.6 on 2020-02-08 17:42

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_auto_20200127_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='likers',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likesCount',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likers',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likesCount',
            new_name='points',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikers',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikers',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
