# Generated by Django 2.2.6 on 2020-02-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200219_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Course'),
        ),
    ]
