# Generated by Django 2.2.6 on 2020-02-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200220_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentPost',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.Post'),
        ),
    ]
