# Generated by Django 2.2.6 on 2020-02-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20200220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(choices=[('QU', "Queen's University"), ('UT', 'University of Toronto'), ('UW', 'University of Waterloo'), ('UWO', 'University of Western Ontario'), ('UG', 'University of Guelph')], editable=False, max_length=4),
        ),
    ]
