# Generated by Django 2.2.6 on 2019-12-21 19:55

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191221_1455'),
        ('userAuth', '0005_auto_20191119_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Course'),
        ),
    ]
