# Generated by Django 2.2.6 on 2020-01-26 01:37

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200125_2037'),
        ('userAuth', '0006_auto_20191221_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Post'),
        ),
    ]
