# Generated by Django 2.2.6 on 2020-01-28 21:18

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200127_2057'),
        ('userAuth', '0007_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.Comment'),
        ),
    ]
